<?php
define('_STATUS_OK', 200);
define('_STATUS_ACCEPTED', 202);
define('_STATUS_NO_CONTENT', 204);
define('_STATUS_MOVED_PERMANENTLY', 301);
define('_STATUS_NOT_MODIFIED', 304);
define('_STATUS_TEMPORARY_REDIRECT', 307);
define('_STATUS_BAD_REQUEST', 400);
define('_STATUS_UNAUTHORIZED', 401);
define('_STATUS_FORBIDDEN', 403);
define('_STATUS_NOT_FOUND', 404);
define('_STATUS_MOETHOD_NOT_ALLOWED', 405);
define('_STATUS_NOT_ACCEPTABLE', 406);
define('_STATUS_PRECONDITION_FAILED', 412);
define('_STATUS_UNSUPPORTED_MEDIA_FILE', 415);
define('_STATUS_INTERNAL_SERVER_ERROR', 500);
define('_STATUS_NOT_IMPLEMNTED', 501);